### ISSUE TITLE
Bug on V9

### ISSUE THREAD

**Issue by Ychabod** [ghost-fvtt/fxmaster#169] opened 2022-01-13 12:26 UTC
### Expected Behavior

Expecting activate and desactivate weather effects? 

### Current Behavior

I have tested effects in order, everything is fine, and when I activate clouds, I've changed some options, and suddenly the effect was gone

### Steps to Reproduce

Create a world with simple world building
Activate module and activate an effect

### Context

Even I uninstall it or desactivate it, and reinstall or activate it, it doesn't work, and produce 10% CPu usage, extreme lag on a map 50x50 for exemple, even when no effects activated

The filter seems working, but not the effect

I've just started to create my campaign, there's one scene with one token, not anymore

### Version

2.2.0

### Foundry VTT Version

v9.242

### Operating System

Windows

### Browser / App

Native Electron App, Firefox

### Game System

Simple world 

### Relevant Modules

None

**Comment by ghost91-** [comment] 2022-01-16 18:09
Hey @Ychabod, I tried to reproduce this issue but was not able to. Could you provide an export of the scene so that I can take a look at it? In order to export the scene, right click the scene in the scene directory and click on the "Export Data" context menu entry.

**Comment by Ychabod** [comment] 2022-01-16 18:29
I've create the same scene with same size, background etc, and its working, don't know where it comes from
Immediately when I click on activate scene, my CPU go to 15% (it's a Ryzen 6 core at4GHz, it can handle it I think) and my foundry goes super slowly

Seems Github can't accept Json attached, here's a Mega link
https://mega.nz/file/ydtGFZJb#hnEyjMzCwh9WclhWDIH1IotHyInxjIimWWCWhMpfQIg

**Comment by Ychabod** [comment] 2022-01-16 18:33
It's probably a bug, I've created the map before installing Fx, and it's my trash map for testing tokens, modules etc, maybe there's something interacting with this module. Anyway, consider it resolved, and let me know if you found something :)

**Comment by ghost91-** [comment] 2022-01-20 21:01
Not sure how it happened, but that scene has a clouds effect with a density of 50. 50 is much too large, resulting in a huge number of clouds. The value should be something between 0 and 1.

I'm closing this, as it's probably not a bug in FXMaster.

**Closed by ghost91-** 2022-01-20 21:01 UTC
Labels: bug, can't reproduce, waiting for feedback
