### ISSUE TITLE
The effects Datastore is not yet connected

### ISSUE THREAD

**Issue by zarazandra** [ghost-fvtt/fxmaster#442] opened 2023-02-23 09:23 UTC
### Expected Behavior

When something's missing, I expect a hint how to solve this. 
Like a "choose folder"-prompt for example or a "detect files"-Button. 

### Current Behavior

![image](https://user-images.githubusercontent.com/70195103/220866243-6b303502-fdff-4ba8-b8bf-77af81939fbf.png)

### Steps to Reproduce

1. start foundry
2. see errormessage

### Context

Since I loaded the module, I get this error message and I have absolutely no clue, how or where I could fix this. There's no further menu oder setting to connect the database and I am absolutely clueless. 

### Version

3.5.2

### Foundry VTT Version

10.291

### Operating System

windows 11

### Browser / App

Native Electron App

### Game System

DSA5 4.2.11

### Relevant Modules

I have no clue...

**Comment by ghost91-** [comment] 2023-02-23 12:47
Have you tried it with all other modules deactivated? If not, please do so.

Also, please take a look at the console (F12) and provide an errors that might be shown there (red messages are errors, yellow ones are warnings). They typically contain more information than just the error message that are in your screenshot.

I am pretty sure that this is not related something in just FXMaster, since I have never seen this issue, but I’ll try it with DSA, to see if there’s maybe a conflict with that system.

**Comment by zarazandra** [comment] 2023-02-25 23:44
Hey, 

with minimal modules the bug doesn't appear. 
(loaded modules:
- Ace Library
- DSA/TDE5 - Interaktive Aventurienkarte
- German [Core]
- lib - Color Settings
- LibWrapper
- Module Profiles
- Optolith to Foundry Importer
- Quick App Scale
- socketlib
- official TDE5-Modules (all)
)



When I add some more modules, I get the error again. Would have to activate and deactivate all of them one after another to pin it down to a single one, but maybe you see already from the list, if one or more of them are causing trouble. 
Full list attached.
![image](https://user-images.githubusercontent.com/70195103/221384584-c16c77a2-15b8-4a1e-ae27-5dbc1f29e9c9.png)
![image](https://user-images.githubusercontent.com/70195103/221384606-e87d2a8a-b58a-41b7-a24b-1cd075b5ec7c.png)
![image](https://user-images.githubusercontent.com/70195103/221384621-1f40731d-f5f2-4c8f-9a7f-e4906451b927.png)
![image](https://user-images.githubusercontent.com/70195103/221384631-cf415eb0-3d1c-4514-baa3-370fcae2a59c.png)
![image](https://user-images.githubusercontent.com/70195103/221384642-86cc7cc5-447c-44f7-9d0a-cb274250cf1f.png)
![image](https://user-images.githubusercontent.com/70195103/221384653-2cc68996-cc13-47cc-bbaf-12032f5a7ec6.png)
![image](https://user-images.githubusercontent.com/70195103/221384660-45b3de07-e025-40a7-a396-77b358d0e080.png)
![image](https://user-images.githubusercontent.com/70195103/221384531-3291c3ba-ccc3-429f-9afd-e2818aad1809.png)

**Comment by ghost91-** [comment] 2023-02-26 09:42
No, unfortunately, I don’t even know many of these. You could try using the „Find the culprit“ module, which allows you to easily find out which module is the problematic one. https://foundryvtt.com/packages/find-the-culprit/

**Comment by zarazandra** [comment] 2023-03-01 09:42
Thank you! That was really helpful.
It seems that "Token Mold" has issues with the addon.

**Comment by ghost91-** [comment] 2023-03-02 12:19
So the issue appears of isung both Token Mold and FXMaster? Then I'll try to reproduce the issue and see if I can do anything about it.

**Comment by ghost91-** [comment] 2023-03-22 20:27
OK, so I just tested it, and it seems the issue happens even with FXMaster disabled. It seems to be purely a problem with Token Mold. So I would recommend you to create an issue at https://github.com/Moerill/token-mold.

Feel free to reference this issue in your new issue over there.

Closing this, as the problem doesn't seem to be related to FXMaster.

**Closed by ghost91-** 2023-03-22 20:27 UTC
Labels: bug, to be confirmed
