### ISSUE TITLE
Per drawing/region filters

### ISSUE THREAD

**Issue by Lazrius** [ghost-fvtt/fxmaster#571] opened 2023-08-05 14:37 UTC
### Description

Currently all effect filters are scene wide, but can be limited by drawings. This is really cool but it means if you want to run certain filters in certain locations you cannot avoid having them both be displayed.

For an example:

The underwater filter when applied to a battlemap with a lake makes the water appear to shimmer and it's a really cool effect. If I have a land section next to this lake, I might want to use the bird filter or some rain to add ambience. In this example, I cannot use the underwater filter for that cool effect, because it will then apply to the rain section as well.

I think it would be awesome if we could define filters at a drawing level where only within the space of a drawing we apply a particular filter.

**Comment by ghost91-** [comment] 2023-08-06 09:09
I don’t fully understand what you mean, you seem to be mixing up some terms. FXMaster has both filter effects and particle effects. You seem to be using the term filter for both, but the distinction is important. They work differently in a fundamental way and filter effects do _not_ support masking at all at the moment.

So I’m not sure if your suggestion is to add masking functionality to filter effects (then this is a duplicate of #68), or to support different masks for different filters (then it is a duplicate of #163), or something completely different. Could you please clarify?

**Comment by Lazrius** [comment] 2023-08-06 21:25
Sorry for poor phrasing. I am hoping to have it where I could draw two separate areas with separate effects. Take this use case:

I have a map. I draw two boxes. In box A I want there to be rain. In box B I want there to be birds. 

I hope that explains it!

**Comment by ghost91-** [comment] 2023-08-07 06:50
Thanks for the explanation. Closing this as a duplicate of #163 then.

**Closed by ghost91-** 2023-08-07 06:50 UTC
Labels: enhancement, waiting for feedback
