### ISSUE TITLE
No weather since 2.0.2

### ISSUE THREAD

**Issue by cs96and** [ghost-fvtt/fxmaster#140] opened 2021-12-31 13:44 UTC
### Expected Behavior

Weather effects (clouds, birds etc) to be shown

### Current Behavior

No weather is shown

### Steps to Reproduce

Add a weather effect to a map (e.g. clouds).

### Context

Tried in Edge and Firefox.  No errors or warnings in console.

Problem still persists in 2.1.0.  2.0.0 and 2.0.1 work fine.

### Version

2.0.2 and 2.1.0

### Foundry VTT Version

0.8.9

### Operating System

Windows 10

### Browser / App

Microsoft Edge

### Game System

dnd5e 1.5.6

### Relevant Modules

no other modules enabled

**Comment by ghost91-** [comment] 2021-12-31 15:15
I can't reproduce the problem, it works perfectly fine for me. Could it be that you have either the "Enable Effects" setting deactivated or the "Disable Effects For Everybody" setting activated? There was a bug that prevented these settings from having any effect, which is fixed now, so if you had either of them set to not show effects, effects would still have been shown in the past, but now it actually prevents them from being shown.

**Comment by cs96and** [comment] 2022-01-01 18:48
I have checked the settings and they are OK.  I have tracked this issue down to a single scene of mine.  I have attached the .json file for the scene which you can import into foundry (using the right click menu of an existing scene - **note it will overwrite that scene!**)

The clouds will work initially, but if you then set the background to the attached image, the clouds and birds will stop working.

[scene.zip](https://github.com/ghost-fvtt/fxmaster/files/7798089/scene.zip)

**Closed** 2022-01-03 23:58 UTC
Labels: bug, confirmed

**Comment by ghost91-** [comment] 2022-01-03 23:59
Thanks for providing the additional data, it helped me a lot with identifying the problem. I have already merged a fix, which will be included in the next release.

**Comment by cs96and** [comment] 2022-01-04 13:26
Can confirm this is now fixed, thanks!
