### ISSUE TITLE
[BUG] No scrollbar in special effects management window in WFRP4e

### ISSUE THREAD

**Issue by Berytak** [ghost-fvtt/fxmaster#538] opened 2023-06-21 13:20 UTC
### Expected Behavior

If you expend the menu and it exceeds it, there should be a scroll bar to scroll through the effects.

### Current Behavior

There is no scroll bar in Warhammer Fantasy Roleplay 4e if the content exceeds the sepecial effects management window.

### Steps to Reproduce

1. Log onto Foundry
2. Open special effects management window
3. Open Folder

### Context

![image](https://github.com/ghost-fvtt/fxmaster/assets/85394657/e3cf0eab-ef06-4144-bd22-b41f21c1a084)

### Version

v4.0.2

### Foundry VTT Version

v11.302

### Operating System

Win11

### Browser / App

Native Electron App, Chrome, Microsoft Edge

### Game System

WFRP4e

**Comment by ghost91-** [comment] 2023-06-21 16:21
Duplicate of #415. There’s nothing I can do on the side of FXMaster, it needs to be fixed in WFRP4e.

**Closed by ghost91-** 2023-06-21 16:21 UTC
Labels: bug, to be confirmed
