### ISSUE TITLE
Crows fill the entire screen if left from v8

### ISSUE THREAD

**Issue by yorickdowne** [ghost-fvtt/fxmaster#123] opened 2021-12-22 21:15 UTC
### Expected Behavior

Birds are small and fly about

### Current Behavior

Huge birds are rendered that fill the entire scene

### Steps to Reproduce

1. Run v8
2. Just FXMaster no other modules
3. Turn on crows
4. Upgrade to v9
5. See crows fill entire screen

### Context

This can be resolved by turning crows off, then turning them on again.

### Version

2.0.0

### Foundry VTT Version

v9.238

### Operating System

NodeJS

### Browser / App

Microsoft Edge

### Game System

dnd5e

**Comment by ghost91-** [comment] 2021-12-22 22:31
Thanks for the report! I just tried it and I can't seem to reproduce the problem. Can you give me a few more details, e.g. your scene dimensions and the grid size? Also, some screenshots of the problem might be helpful. Can you reliably reproduce the problem or was this just a one time thing?

**Comment by yorickdowne** [comment] 2021-12-22 23:00
This was a one-time thing after upgrading - disabling and re-enabling crows fixed it. Happy to get you dimensions, will edit.
I consider this extremely low urgency since “turn it off and on again” fixed it.

**Comment by himmelweiss** [comment] 2021-12-27 11:01
Just had the same problem.
Fresh Foundry V9 (stable) install.

Turning crows off then on again fixed it.

![fxmaster_spur_im_wald](https://user-images.githubusercontent.com/7482909/147465429-7de4c07d-8762-4fb8-8361-a15c29753977.jpg)

**Comment by Grizzly90** [comment] 2021-12-27 11:09
You can try to reproduce this with the scenes in the module "The Dark Eye - Introduction Adventure".

**Comment by ghost91-** [comment] 2021-12-27 13:05
Ah, is this for scenes that are imported from a compendium provided by a module, that are imported after the migration has already been performed? The migrations don’t touch compendiums provided by other packages, because it would be overwritten anyways when those packages are updated. The authors of those packages will need to update their packages accordingly, unfortunately.

**Comment by Grizzly90** [comment] 2021-12-27 13:27
idk whats about @yorickdowne, but @himmelweiss is using the DSA compendium. "Spur im Wald" is one of its scenes
Plushtoast already pushed a update for the FXmaster changes for this module (the update won't work atm, but that's another issue)

**Comment by yorickdowne** [comment] 2021-12-27 13:59
My scene wasn’t hiding in a compendium. It’s a scene that was created in 0.8 and had crows enabled in 0.8, and then had issues after upgrade to v9.

If there’s a change that’s supposed to happen to the fxmaster settings of the scene when migrating to v9, maybe it’s that migration that’s not 100%.

Easy enough to work around though. I am not worried.

**Comment by ghost91-** [comment] 2021-12-27 14:25
No, FXMaster works the same in Foundry 0.8.x and V9. The only migration that happens for FXMaster is related to updating FXMaster to version 2. But that’s completely independent from the foundry version.

So you are saying, you were already using FXMaster 2.0.0 in foundry 0.8.x and after updating to Foundry V9, this issue occurred?


regarding the issue observed by the others, this indeed looks like it’s a problem of that module then. Good if the author is already working on it :)

**Comment by yorickdowne** [comment] 2021-12-27 14:37
I am not sure what version of fxmaster I had in 0.8 - whatever would have come in as “the latest”. I did not however touch that scene for a while in 0.8, it did not get opened/switched to with latest of fxmaster in 0.8. It was used again for testing after upgrade to v9.

**Comment by ghost91-** [comment] 2021-12-27 14:46
Ok, then it may have already been broken in 0.8. There were some adjustments to data in the past in FXMaster, before I took over. So if you didn’t create the scene with the latest version of FXMaster before 2.0.0 (which is 1.2.1), that may be the reason for the problem. I had one report for that, but it was a _really_ old scene that hadn’t been touched since April or so.

I think I’m just going to close this as I cannot reproduce the issue, making it practically impossible to fix, and also because there is an easy workaround.

If something similar occurs again in a reproducible way, feel free to reopen this or create a new issue.

**Closed by ghost91-** 2021-12-27 14:46 UTC
Labels: bug, to be confirmed
