### ISSUE TITLE
Unable to keep the FX Menu open

### ISSUE THREAD

**Issue by lbnesquik** [ghost-fvtt/fxmaster#341] opened 2022-08-19 15:42 UTC
### Expected Behavior

When opening the menu, that it would stay open.

### Current Behavior

View the gif for a clear description.

### Steps to Reproduce

View the gif for a clear description.

### Context

![Foundry_Virtual_Tabletop_2022-08-19_17-40-36](https://user-images.githubusercontent.com/24830358/185656250-b38cf211-7288-493d-957d-0ca075cab2f1.gif)

### Version

2.7.1

### Foundry VTT Version

9.269

### Operating System

Windows 10

### Browser / App

Other

### Game System

Dnd 5e 163

**Comment by ghost91-** [comment] 2022-08-19 21:03
I can't reproduce the issue here. You chose "Other" for "Browser/App", so what are you actually using?

Have you tried uninstalling and reinstalling FXMaster?

**Comment by ghost91-** [comment] 2022-09-11 14:33
Closing this as non reproducible.

**Closed by ghost91-** 2022-09-11 14:33 UTC
Labels: bug, can't reproduce, waiting for feedback
